name 'jm-acmeair-default-assets'
maintainer 'Christian Davatz'
maintainer_email 'crixx@davatz.eu'
license 'all_rights'
description 'Installs/Configures jm-acmeair-default-assets'
long_description 'Installs/Configures jm-acmeair-default-assets'
version '0.1.0'