name 'cwb-tuning'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cwb-tuning'
long_description 'Installs/Configures cwb-tuning'
version '0.1.0'
