name 'cwb-jmeter'
maintainer 'Christian Davatz'
maintainer_email 'crixx@davatz.eu'
license 'all_rights'
description 'Installs/Configures cwb-jmeter'
long_description 'Installs/Configures cwb-jmeter'
version '0.1.0'

depends 'apt', '~> 2.9.2'
depends 'firewall', '~> 2.4.0'
depends 'java', '~> 1.39.0'