name 'acmeair_wlp_morphia_distributed'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures acmeair_wlp_morphia_distributed'
long_description 'Installs/Configures acmeair_wlp_morphia_distributed'
version '0.1.0'

depends 'apt', '~> 2.9.2'
depends 'firewall', '~> 2.4.0'
depends 'java', '~> 1.39.0'
depends 'wlp', '~> 0.3.0'