name 'cwb-monitoring'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cwb-monitoring'
long_description 'Installs/Configures cwb-monitoring'
version '0.1.0'
